server:
  port: 8083
  tomcat:
    accept-count: 2000
    max-connections: 10000

spring:
  application:
    name: payment-service
  datasource:
    hikari:
      maximum-pool-size: 80
      minimum-idle: 20
      connection-timeout: 3000
      validation-timeout: 1000
      idle-timeout: 600000
      max-lifetime: 1800000
      leak-detection-threshold: 5000
    url: jdbc:mysql://localhost:3316/vetautet_payment?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
    username: root
    password: root1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    type: com.zaxxer.hikari.HikariDataSource

  jpa:
    database: mysql
    show-sql: true
    hibernate:
      ddl-auto: none

  data:
    redis:
      host: 127.0.0.1
      port: 6319
      password: ""
      lettuce:
        pool:
          max-active: 10
          max-idle: 5
          min-idle: 5
      connect-timeout: 30000

  threads:
    virtual:
      enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
    prometheus:
      enabled: true
  metrics:
    tags:
      application: ${spring.application.name}
